dist: trusty
sudo: required

services:
  - docker

language: python
python:
  - "2.7"
install:
  # Start PostgreSQL
  - sudo service postgresql stop
  - docker run -d --name pg -e POSTGRES_USER=test -e POSTGRES_PASSWORD=test -e POSTGRES_DB=ukb -p 5432:5432 postgres:11
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - hash -r
  # Install bgenix
  - wget http://code.enkre.net/bgen/tarball/release/bgen.tgz
  - tar -xzf bgen.tgz
  - cd bgen.tgz
  - ./waf configure
  - ./waf
  - ./build/test/unit/test_bgen
  - sudo cp ./build/apps/bgenix /usr/local/bin/
  - cd ..
  - sudo cp lib/qctool/* /usr/local/bin/
  # Install conda and create environment
  - source /home/travis/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -q -n test-environment --file environment.yml
  - conda activate test-environment
  #  - sleep 10

script: nosetests --with-coverage

after_success:
  coveralls
